version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: "shareable-notes-jaeger"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - shareable-notes

  share-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "shareable-notes-share-service"
    command: [
      "share",
      "start",
      "-c",
      "share-config.yml"
    ]
    environment:
      JAEGER_AGENT_HOST: shareable-notes-jaeger
      JAEGER_AGENT_PORT: 6831
    volumes:
      - ./conf/share-config.yml:/conf/share-config.yml
    ports:
      - "8081:8080"
      - "50051:50051"
    networks:
      - shareable-notes
    depends_on:
      - consul
      - jaeger

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "shareable-notes-gateway"
    command: [
      "gateway",
      "start",
      "-c",
      "gateway-config.yml"
    ]
    environment:
      - JAEGER_AGENT_HOST=shareable-notes-jaeger
      - JAEGER_AGENT_PORT=6831
    volumes:
      - ./conf/gateway-config.yml:/conf/gateway-config.yml
    ports:
      - "8080:8080"
    networks:
      - shareable-notes
    depends_on:
      - share-microservice
      - consul
      - jaeger

  consul:
    image: consul
    container_name: "shareable-notes-consul"
    command: agent -server -bootstrap -ui -client=0.0.0.0
    ports:
      - 8500:8500
      - 8600:8600/udp
    networks:
      - shareable-notes

  mongo:
    image: mongo
    container_name: "shareable-notes-mongo"
    networks:
      - shareable-notes
    environment:
      MONGO_INITDB_ROOT_USERNAME: uni
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - shareable-notes-mongo:/data/db
    ports:
      - "27017:27017"

  cadvisor:
    image: "gcr.io/google-containers/cadvisor"
    container_name: "shareable-notes-cadvisor"
    ports:
      - "9091:8080"
    networks:
      - shareable-notes
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    container_name: "shareable-notes-prometheus"
    ports:
      - "9090:9090"
    networks:
      - shareable-notes
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
      - grafana
      - share-microservice
      - gateway

  grafana:
    image: grafana/grafana
    container_name: "shareable-notes-grafana"
    ports:
      - "9093:3000"
    networks:
      - shareable-notes
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=shareable-notes
      - GF_USERS_ALLOW_SIGN_UP=false

  node-exporter:
    image: prom/node-exporter
    container_name: "shareable-notes-exporter"
    ports:
      - "9092:9100"
    networks:
      - shareable-notes

networks:
  shareable-notes:
    external: false

volumes:
  shareable-notes-mongo:
    external: false

