share-svc:
  name: "Share-Service-GRPC"
  apis:
    ShareNote:
      path: "/v1"
      method: "POST"
      ratelimit:
        delta: 1000
        duration: 1s
      breaker:
        name: "ShareNote"
        timeout: 30s
    PrivateNote:
      path: "/v1/private"
      method: "POST"
      ratelimit:
        delta: 1000
        duration: 1s
      breaker:
        name: "PrivateNote"
        timeout: 30s
    GetNote:
      path: "/v1/note/{id}"
      method: "GET"
      ratelimit:
        delta: 1000
        duration: 1s
      breaker:
        name: "GetNote"
        timeout: 30s
zipkin:
  bridge: true
  tracer:
    endpoint:
      name: share
      address: 127.0.0.1:8080
  reporter:
    url: margin-zipkin:9411/api/v2/spans