## prometheus.yml ##

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

#rule_files:
#  - '/etc/prometheus/alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'share'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['margin-share-service:8080']
        labels:
          group: 'share'

  - job_name: 'gateway'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ 'margin-gateway:8080']
        labels:
          group: 'gateway'


  - job_name: 'cadvisor'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['margin-cadvisor:8080']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['margin-exporter:9100']