address: "http://localhost:8080"
host: shareable-notes-share-service
service:
  name: "Share"
  apis:
    ShareNote:
      name: "ShareNote"
      path: "/"
      method: "POST"
      ratelimit:
        delta: 1000
        duration: 1s
      breaker:
        name: "ShareNote"
        timeout: 30s
    PrivateNote:
      name: "PrivateNote"
      path: "/private"
      method: "POST"
      ratelimit:
        delta: 1000
        duration: 1s
      breaker:
        name: "PrivateNote"
        timeout: 30s
    GetNote:
      name: "GetNote"
      path: "/note/{id}"
      method: "GET"
      ratelimit:
        delta: 1000
        duration: 1s
      breaker:
        name: "GetNote"
        timeout: 30s

mongo:
  auth:
    username: shareable-notes
    password: secret
  hosts: ["shareable-notes-mongo:27017"]
  database: shareable-notes
  collection: notes
  connect-timeout: 30s

consul:
  agent-service-registration:
    address: "shareable-notes-share-service"
    port: 50051
  client:
    address: "shareable-notes-consul:8500"
    scheme: "http"

http:
  name: "Share-Service-HTTP"
  port: "8080"
  read-timeout: 15s
  write-timeout: 15s

grpc:
  name: "Share-Service-GRPC"
  port: "50051"

prometheus:
  path: "/metrics"
  counter-options:
    ShareNote:
      namespace: share
      name: note
      help: "Total requests deal with by share_note"
      subsystem: share
    PrivateNote:
      namespace: share
      name: note
      help: "Total requests deal with by private_note"
      subsystem: private
    GetNote:
      namespace: share
      name: note
      help: "Total requests deal with by get_note"
      subsystem: get
  summary-options:
    ShareNote:
      namespace: share
      name: note_duration
      help: "share_note duration in seconds"
      subsystem: share
      label-names: ["success"]
    PrivateNote:
      namespace: share
      name: note_duration
      help: "private_note duration in seconds"
      subsystem: private
      label-names: ["success"]
    GetNote:
      namespace: share
      name: note_duration
      help: "get_note duration in seconds"
      subsystem: get
      label-names: ["success"]