name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-141.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # framework
  get: ^3.24.0

  # animation
  animations: ^1.1.2
  simple_animations: ^3.0.0-nullsafety.2
  circular_reveal_animation: ^2.0.0-nullsafety.0
  
  # widgets
  modal_bottom_sheet: ^2.0.0-nullsafety.1
  flutter_slidable: ^0.6.0-nullsafety.0
  diffutil_sliverlist: ^0.5.0-nullsafety.0
  morphing_text: ^1.0.0-nullsafety.0
  flash: ^1.4.0-nullsafety
  flutter_animated_play_button: ^0.1.3+2
  flutter_rating_bar: ^4.0.0-nullsafety.0
  flutter_keyboard_visibility: ^5.0.0-nullsafety.0
  # dotted_border: ^2.0.0-nullsafety.0
  grouped_list: ^4.0.0-nullsafety.1
  formz: ^0.4.0-nullsafety.0
  # barcode_widget: ^2.0.0-nullsafety.1
  fluttertoast: ^8.0.0-nullsafety.0

  # route
  flutter_modular: ^3.0.0-nullsafety.27
  circular_clip_route: ^0.2.0-nullsafety.0

  # sugar
  supercharged: ^2.0.0-nullsafety.1
  nested: ^0.0.5-nullsafety.1
  money2: ^2.0.1-nullsafety.6
  # list_ext: ^1.0.1-nullsafety.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  sprintf: ^6.0.0-nullsafety

  # Authentication
  sign_in_with_apple: ^3.0.0-nullsafety.0

  # icons
  cupertino_icons: ^1.0.1
  # flutter_svg: ^0.20.0-nullsafety.3

  # serialize
  json_annotation: ^4.0.0-nullsafety.0

  # local storage
  sqflite: ^2.0.0-nullsafety.2
  shared_preferences: ^0.5.12+4
  path: ^1.8.0-nullsafety.3

  # code quality
  pedantic: ^1.10.0-nullsafety.3

  # io
  pdf: ^2.0.0
  file_picker: ^3.0.0-nullsafety.1

  # logic
  flutter_hooks: ^0.15.0
  flutter_bloc: ^7.0.0-nullsafety.0

  # DI
  injectable: ^1.0.7
  get_it: ^5.0.3

  # html
  url_launcher: ^6.0.0-nullsafety.1

  # video
  video_player: ^2.0.0-nullsafety.4

  # network
  connectivity: ^3.0.0-nullsafety.1
  dio: ^3.0.10

  # device
  device_info: ^2.0.0-nullsafety.1

  # concurrency
  synchronized: ^3.0.0-nullsafety.1
  mutex: ^2.0.0-nullsafety.0

  # configuration
  envify: ^2.0.0

  # utils
  pausable_timer: ^0.2.0-nullsafety.0
  widgets_visibility_provider: ^3.0.0-nullsafety.0

  openapi_generator_annotations: ^3.0.0-nullsafety.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^4.0.0-nullsafety.0
  mockito: ^5.0.0-nullsafety.1
  build_runner: ^1.10.11
  injectable_generator: ^1.0.7
  logger: ^1.0.0-nullsafety.0
  openapi_generator: ^3.0.0-nullsafety.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
